### ISSUE TITLE
mod_wsgi installation fails 

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppetboard#207]
Hey all,

I've tried following the mod_wsgi instructions, but I was not able to get this working! 

## In the browser I see this:
 
    Internal Server Error
 
    The server encountered an internal error or misconfiguration and was unable to complete your request.
 
    Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
 
    More information about this error may be available in the server error log.

## In the apache error logs I see:

    [Sat Jan 16 18:15:56.788775 2016] [:error] [pid 21692] [client 69.113.164.162:44023]     from puppetboard.app import app as application
    [Sat Jan 16 18:15:56.788839 2016] [:error] [pid 21692] [client 69.113.164.162:44023]   File "/usr/lib/python2.7/site-packages/puppetboard/app.py", line 88, in <module>
    [Sat Jan 16 18:15:56.789221 2016] [:error] [pid 21692] [client 69.113.164.162:44023]     envs = environments()
    [Sat Jan 16 18:15:56.789244 2016] [:error] [pid 21692] [client 69.113.164.162:44023]   File "/usr/lib/python2.7/site-packages/puppetboard/app.py", line 73, in environments
    [Sat Jan 16 18:15:56.789293 2016] [:error] [pid 21692] [client 69.113.164.162:44023]     envs = get_or_abort(puppetdb.environments)
    [Sat Jan 16 18:15:56.789312 2016] [:error] [pid 21692] [client 69.113.164.162:44023]   File "/usr/lib/python2.7/site-packages/puppetboard/utils.py", line 26, in get_or_abort
    [Sat Jan 16 18:15:56.789383 2016] [:error] [pid 21692] [client 69.113.164.162:44023]     abort(e.response.status_code)
    [Sat Jan 16 18:15:56.789397 2016] [:error] [pid 21692] [client 69.113.164.162:44023]   File "/usr/lib/python2.7/site-packages/werkzeug/exceptions.py", line 646, in __call__
    [Sat Jan 16 18:15:56.789626 2016] [:error] [pid 21692] [client 69.113.164.162:44023]     raise self.mapping[code](*args, **kwargs)
    [Sat Jan 16 18:15:56.789713 2016] [:error] [pid 21692] [client 69.113.164.162:44023] NotFound: 404: Not Found

## This is my apache config:
 
    <VirtualHost *:80>
        ServerName puppetboard.example.com
        WSGIDaemonProcess puppetboard user=apache group=apache threads=5
        WSGIScriptAlias / /var/www/puppetboard/wsgi.py
        ErrorLog /var/log/httpd/puppetboard.error.log
        CustomLog /var/log/httpd/puppetboard.access.log combined
 
        Alias /static /usr/lib/python2.7/site-packages/puppetboard/static
            <Directory /usr/lib/python2.7/site-packages/puppetboard/static>
            Satisfy Any
            Allow from all
        </Directory>
 
        <Directory /usr/lib/python2.7/site-packages/puppetboard/static>
            WSGIProcessGroup puppetboard
            WSGIApplicationGroup %{GLOBAL}
            Require all granted
        </Directory>
    </VirtualHost>
 
## Apache and mod_wsgi versions
 
    [root@puppet:/etc/httpd/conf.d] #rpm -qa | grep mod_wsgi
    mod_wsgi-3.4-12.el7_0.x86_64
    [root@puppet:/etc/httpd/conf.d] #rpm -qa | grep httpd
    httpd-2.4.6-31.el7.centos.x86_64
    httpd-tools-2.4.6-31.el7.centos.x86_64

## This is my OS version:

    [root@puppet:~] #cat /etc/redhat-release
    CentOS Linux release 7.2.1511 (Core)

What am I doing wrong, and how can I get this working?

**Comment by corey-hammerton** [comment]
- Are you running PuppetDB 3.x? Versions 0.1.x only work with 3.0 and higher.
- What environment(s) do you have available, by default if the default 'production' environment is not found a 404 is given, you can try switching environments from the menu to give you results. 
-- Future versions will treat this situation better.

**Comment by corey-hammerton** [comment]
@bluethundr are you still experiencing this issue? Have you tried installing 0.1.2 and configuring a default environment?

**Comment by tylermauthe** [comment]
I am having the same issue on CentOS 6.

I installed 0.1.2 and I'm still having the same issues.

I am running the latest PuppetDB and production is one of my environments.

If I understand the error correctly, does that mean the pypuppetdb client is failing to retrieve a list of environments from PuppetDB?

**Comment by tylermauthe** [comment]
Sorry, I lied... I'm not getting the same error, but it looks deceptively similar:

```
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8] mod_wsgi (pid=3600): Exception occurred processing WSGI script '/var/www/html/puppetboard/wsgi.py'., referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8] Traceback (most recent call last):, referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__, referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]     return self.wsgi_app(environ, start_response), referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app, referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]     response = self.make_response(self.handle_exception(e)), referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1410, in handle_exception, referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]     return handler(e), referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]   File "/usr/local/lib/python2.7/site-packages/puppetboard/app.py", line 122, in server_error, referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]     envs = environments(), referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]   File "/usr/local/lib/python2.7/site-packages/puppetboard/app.py", line 71, in environments, referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]     envs = get_or_abort(puppetdb.environments), referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]   File "/usr/local/lib/python2.7/site-packages/puppetboard/utils.py", line 28, in get_or_abort, referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]     abort(500), referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]   File "/usr/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 646, in __call__, referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8]     raise self.mapping[code](*args, **kwargs), referer: http://puppetboard.workplace.com/
[Thu Mar 17 15:43:01 2016] [error] [client 8.8.8.8] InternalServerError: 500: Internal Server Error, referer: http://puppetboard.workplace.com/
```

Let me know if you want to create a new issue, I suspect that this is the same issue though.

**Comment by corey-hammerton** [comment]
@tylermauthe what version of PuppetDB are you running?

**Comment by corey-hammerton** [comment]
Closing due to lack of activity.

**Comment by tylermauthe** [comment]
Sorry, missed your ping. I fixed my issue after a bunch of Apache configuration hassles.

I think it was an issue with running Puppetboard on the same server as some other strange services. I'm going to recreate it on it's own VM.
