### ISSUE TITLE
Divide by zero in aggregate metrics['avg_resources_node'] calculation

### ISSUE THREAD

**Issue by ryno75** [voxpupuli/puppetboard#240]
Found a corner case where if an environment has zero nodes in it app.py will try to divide by zero and 500 with this:

```
[Thu May 12 18:07:08 2016] [error] ERROR:puppetboard.app:Exception on /dev/ [GET]
[Thu May 12 18:07:08 2016] [error] Traceback (most recent call last):
[Thu May 12 18:07:08 2016] [error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Thu May 12 18:07:08 2016] [error]     response = self.full_dispatch_request()
[Thu May 12 18:07:08 2016] [error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu May 12 18:07:08 2016] [error]     rv = self.handle_user_exception(e)
[Thu May 12 18:07:08 2016] [error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Thu May 12 18:07:08 2016] [error]     reraise(exc_type, exc_value, tb)
[Thu May 12 18:07:08 2016] [error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu May 12 18:07:08 2016] [error]     rv = self.dispatch_request()
[Thu May 12 18:07:08 2016] [error]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Thu May 12 18:07:08 2016] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu May 12 18:07:08 2016] [error]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 178, in index
[Thu May 12 18:07:08 2016] [error]     (num_resources[0]['count'] / num_nodes[0]['count']))
[Thu May 12 18:07:08 2016] [error] ZeroDivisionError: integer division or modulo by zero
```

Just adding a check for a zero denominator and setting the metrics[avg_resources_node'] to zero will skirt the issue.  Pull request coming...

**Comment by corey-hammerton** [comment]
Already fixed with https://github.com/voxpupuli/puppetboard/pull/221, fix is not yet released.

**Comment by ryno75** [comment]
Oh! haha.. wow. not sure how I missed that.  Obviously #221 hasn't yet been merged but apparently I need to search the issues better next time!  Cool.

I considered adding a try/except handler as well, but I prefer to completely skip the Exception if easily possible. Thanks.

**Comment by corey-hammerton** [comment]
hmm, good catch. I don't know how that wasn't properly merged. I'll redo that PR.
