### ISSUE TITLE
Facts not showing (blank screen)

### ISSUE THREAD

**Issue by chris-bmj** [voxpupuli/puppetboard#302]
For example the 'apt_has_updates' fact from the puppetlabs apt module.  It works at the command line, returning a boolean, but puppetboard shows a blank screen. Apache log shows the following:

[Wed Sep 07 09:09:22.373939 2016] [:error] [pid 12070:tid 140324810737408] [client 10.1.172.85:58784] UndefinedError: 'bool object' has no attribute 'replace', referer: http://puppetboard.company.com/sandpit/facts

This is not limited to booleans.  The 'apt_security_updates' fact returns an int, and gets the following error:

[Wed Sep 07 09:11:22.646618 2016] [:error] [pid 12070:tid 140324877879040] [client 10.1.172.85:58840] UndefinedError: 'int object' has no attribute 'replace', referer: http://puppetboard.company.com/sandpit/facts

Regards
Chris

**Comment by chris-bmj** [comment]
I've found out that this only happens if the problem fact appears in the GRAPH_FACTS array.

**Comment by juniorsysadmin** [comment]
Anyone else able to reproduce and verify as a bug?

**Comment by schildwaechter** [comment]
We ran into the same issue with the `processorcount` fact where we saw an empty facts page but no error.
After dropping it from `GRAPH_FACTS` it worked again.

**Comment by smortex** [comment]
Here is a full backtrace when trying to access `/fact/is_pe` with `is_pe`  included into `GRAPH_FACTS`:

```
App 8650 stderr: [ pid=8650, time=2017-02-05 15:47:44,693 ]: WSGI application raised an exception!
App 8650 stderr: Traceback (most recent call last):
App 8650 stderr:   File "/usr/local/lib/ruby/gems/2.3/gems/passenger/src/helper-scripts/wsgi-loader.py", line 163, in main_loop
App 8650 stderr:     socket_hijacked = self.process_request(env, input_stream, client)
App 8650 stderr:   File "/usr/local/lib/ruby/gems/2.3/gems/passenger/src/helper-scripts/wsgi-loader.py", line 302, in process_request
App 8650 stderr:     for data in result:
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 703, in __next__
App 8650 stderr:     return self._next()
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 81, in _iter_encoded
App 8650 stderr:     for item in iterable:
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/flask/helpers.py", line 130, in generator
App 8650 stderr:     for item in gen:
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1208, in __next__
App 8650 stderr:     return self._next()
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1190, in generator
App 8650 stderr:     c = next()
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in generate
App 8650 stderr:     yield self.environment.handle_exception(exc_info, True)
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
App 8650 stderr:     reraise(exc_type, exc_value, tb)
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/puppetboard/templates/fact.html", line 2, in top-level template code
App 8650 stderr:     {% import '_macros.html' as macros %}
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/puppetboard/templates/layout.html", line 50, in top-level template code
App 8650 stderr:     {% block javascript %} {% endblock javascript %}
App 8650 stderr:   File "/usr/local/lib/python2.7/site-packages/puppetboard/templates/fact.html", line 10, in block "javascript"
App 8650 stderr:     label: '{{ fact.grouper.replace("\n", " ") }}',
App 8650 stderr: UndefinedError: 'bool object' has no attribute 'replace'
```

This is puppetboard 0.2.1

It seems that *any boolean fact* (e.g. `is_pe`, `is_virtual`, `selinux`) produce this breakage.

**Comment by gdubicki** [comment]
Closing as outdated. Please reopen if you still experience such problem with the current version of the Puppetboard.
