### ISSUE TITLE
Puppetboard doesn't start because of @app.errorhandler(204) error

### ISSUE THREAD

**Issue by thias** [voxpupuli/puppetboard#345]
This is with f016820d3a18267f888555cdb046d3d2e8eb3ed8, latest commit on master as of right now.

I just ran : `pip install --user git+https://github.com/voxpupuli/puppetboard.git@master`

And got the following : 
```
[puppetboard@peanut site-packages]$ ls
click                             puppetboard
click-6.7.dist-info               puppetboard-0.2.0-py2.7.egg-info
flask                             pypuppetdb
Flask-0.12.dist-info              pypuppetdb-0.3.2.dist-info
flask_wtf                         requests
Flask_WTF-0.13-py2.7.egg-info     requests-2.13.0.dist-info
itsdangerous-0.24-py2.7.egg-info  test
itsdangerous.py                   tests
itsdangerous.pyc                  werkzeug
jinja2                            Werkzeug-0.11.15.dist-info
Jinja2-2.9.5.dist-info            wtforms
markupsafe                        WTForms-2.1-py2.7.egg-info
MarkupSafe-0.23-py2.7.egg-info
```
I've configured Puppetboard to run from a systemd service (this is RHEL7) : 
```
[Service]
User=puppetboard
WorkingDirectory=/home/puppetboard
ExecStart=/sbin/uwsgi --socket :3000 --plugin python --wsgi-file uwsgi.py
```
First issue is that Puppetboard doesn't even start : 
```
Starting Puppetboard...
*** Starting uWSGI 2.0.14 (64bit) on [Wed Feb  1 09:40:06 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 25 January 2017 15:08:40
os: Linux-3.10.0-514.6.1.el7.x86_64 #1 SMP Sat Dec 10 11:15:38 EST 2016
nodename: peanut.example.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/puppetboard
detected binary path: /usr/sbin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 31226
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :3000 fd 3
Python version: 2.7.5 (default, Aug  2 2016, 04:20:16)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xcb5ee0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
/home/puppetboard/.local/lib/python2.7/site-packages/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
from flask.ext.wtf import Form
/home/puppetboard/.local/lib/python2.7/site-packages/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
class QueryForm(Form):
/home/puppetboard/.local/lib/python2.7/site-packages/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
class CatalogForm(Form):
Traceback (most recent call last):
File "uwsgi.py", line 6, in <module>
from puppetboard.app import app as application
File "/home/puppetboard/.local/lib/python2.7/site-packages/puppetboard/app.py", line 119, in <module>
@app.errorhandler(204)
File "/home/puppetboard/.local/lib/python2.7/site-packages/flask/app.py", line 1159, in decorator
self._register_error_handler(None, code_or_exception, f)
File "/home/puppetboard/.local/lib/python2.7/site-packages/flask/app.py", line 64, in wrapper_func
return f(self, *args, **kwargs)
File "/home/puppetboard/.local/lib/python2.7/site-packages/flask/app.py", line 1185, in _register_error_handler
exc_class, code = self._get_exc_class_and_code(code_or_exception)
File "/home/puppetboard/.local/lib/python2.7/site-packages/flask/app.py", line 1104, in _get_exc_class_and_code
exc_class = default_exceptions[exc_class_or_code]
KeyError: 204
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 19396, cores: 1)
```
Once I comment out the section about _"204 doesn't have a mapping in werkzeug"_ in `app.py`, then it starts up fine.

**Comment by mterzo** [comment]
I'll need to set it up with uwsgi, i'm running it now without.  My Werkzeug is pined at 0.11.10.  I'm gonna have to look into see if they removed the 204 from 0.11.10 to 0.11.15, 204 is NoContent.

**Comment by mterzo** [comment]
Oh, and you are also running Flask 0.12, I've seen other issues, big changes form 10 to 12.

**Comment by mterzo** [comment]
https://travis-ci.org/mterzo/puppetboard/jobs/186296824

I have a development branch getting to the latest release.

**Comment by thias** [comment]
Yeah, there are also 3 FlaskWTFDeprecationWarning lines in that output.

The versions I have are all the ones automatically pulled in by the pip command to install Puppetboard, so my understanding is that anyone installing Puppetboard for the first time as of right now will get those.

Ah, the joys of forward/backward compatibility! At least Python is used to it... *cough* try/except *cough* :-)

**Comment by mterzo** [comment]
Yeah, I'm about to modify the setup.py to not limit it the version that is expected.

I'm having a fun time with the Jinja2 template and scooping.
