### ISSUE TITLE
virtualenv fails: no module named packaging.version

### ISSUE THREAD

**Issue by KlavsKlavsen** [voxpupuli/puppetboard#379]
```
# virtualenv --system-site-packages -p python /srv/puppetboard/virtenv-puppetboard && /srv/puppetboard/virtenv-puppetboard/bin/pip wheel --help > /dev/null 2>&1 && { /srv/puppetboard/virtenv-puppetboard/bin/pip wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-use-wheel'; } ; { /srv/puppetboard/virtenv-puppetboard/bin/pip --log /srv/puppetboard/virtenv-puppetboard/pip.log install   $wheel_support_flag --upgrade pip setuptools || /srv/puppetboard/virtenv-puppetboard/bin/pip --log /srv/puppetboard/virtenv-puppetboard/pip.log install    --upgrade pip setuptools ;}
Running virtualenv with interpreter /bin/python
New python executable in /srv/puppetboard/virtenv-puppetboard/bin/python
Installing Setuptools.............................................................................................done.
Installing Pip....................................................................................................................................done.

Usage:   
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-use-wheel
Downloading/unpacking pip from https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz#md5=35f01da33009719497f01a4ba69d63c9
  Downloading pip-9.0.1.tar.gz (1.2MB): 1.2MB downloaded
  Running setup.py egg_info for package pip
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.landscape.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.github'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
Downloading/unpacking setuptools from https://pypi.python.org/packages/d5/b7/e52b7dccd3f91eec858309dcd931c1387bf70b6d458c86a9bfcb50134fbd/setuptools-34.3.3.zip#md5=696941b10b15f0717be957a4d6cfc12e
  Downloading setuptools-34.3.3.zip (622kB): 622kB downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named packaging.version
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named packaging.version

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /srv/puppetboard/virtenv-puppetboard/build/setuptools
Storing complete log in /root/.pip/pip.log
Traceback (most recent call last):
  File "/srv/puppetboard/virtenv-puppetboard/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pip/basecommand.py", line 176, in main
    logger.fatal('Storing complete log in %s' % log_fn)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pip/log.py", line 48, in fatal
    self.log(self.FATAL, msg, *args, **kw)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pip/log.py", line 75, in log
    backwardcompat.fwrite(consumer, rendered)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pip/backwardcompat/__init__.py", line 90, in fwrite
    f.write(s)
ValueError: I/O operation on closed file
```

**Comment by mterzo** [comment]
Can you use, the module puppet module https://github.com/voxpupuli/puppet-puppetboard

**Comment by KlavsKlavsen** [comment]
I am using that module. it runs the above command - which fails as described. I then tried to rerun the command by hand - and it fails the same wayas shown above.

**Comment by mterzo** [comment]
Figured as much what's the environment.

**Comment by KlavsKlavsen** [comment]
centos 7. It worked a few months ago, when I last did it..

**Comment by tux-o-matic** [comment]
It's not failing on PuppetBoard but on setuptools.

**Comment by ju5t** [comment]
I ran into the same problem. I didn't really look into the Puppet side of the solution but for me the solution was to install all requirements manually.

```
source /srv/puppetboard/virtenv-puppetboard/bin/activate
pip install -r /srv/puppetboard/puppetboard/requirements.txt
```

**Comment by mterzo** [comment]
@ju5t Yeah, that's not quite the same since puppet-puppetboard is doing an --upgrade pip.

**Comment by gdubicki** [comment]
This issue is referring to Python 2 for which support has been dropped long time ago. Therefore I am closing it. Please reopen if you have a similar problem with the current version of Puppetboard using Python 3, @KlavsKlavsen .
