### ISSUE TITLE
Internal Server Error when viewing reports

### ISSUE THREAD

**Issue by phybros** [voxpupuli/puppetboard#383]
Everything on my install works great, except if go to "Reports" or load up a Node (its list of reports never populates - everything else shows fine).

Where the data table of Reports should be it just says Processing... and then in the console there's a 500. Tracing that into the logs I see this:

```
ERROR:pypuppetdb.api:Illegal value '{:field "end_time", :order "None"}' in :order_by; 'order' must be either 'asc' or 'desc' puppetdb.dev.local:8080 over HTTP.
```

Here is `settings.py`

```
DEV_LISTEN_HOST = '127.0.0.1'
DEV_LISTEN_PORT = 5000
LOGLEVEL = 'info'
PUPPETDB_HOST = 'puppetdb.dev.local'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = False
PUPPETDB_TIMEOUT = 20
UNRESPONSIVE_HOURS = 3
ENABLE_CATALOG = False
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
OFFLINE_MODE = False
PUPPETDB_EXPERIMENTAL = False
DEFAULT_ENVIRONMENT = 'dev'
REPORTS_COUNT = 10
```

I'm sure its something I'm doing wrong, but what could be going on here? I'm on PuppetDB 4.3.2

**Comment by mterzo** [comment]
I'm on 4.3.0 and working.

Add:
```
OVERVIEW_FILTER = None
```
What version of puppetboard board and pypupetdb are you using?

**Comment by phybros** [comment]
@mterzo Adding `OVERVIEW_FILTER = None` didn't change anything. I'm running Puppetboard `0.2.2` and pypuppetdb `0.3.2`. I'm installing using the Puppet module: https://github.com/voxpupuli/puppet-puppetboard

**Comment by tux-o-matic** [comment]
One of my Puppet master happens to be on the same PuppetDB/board/pypuppetdb versions and I can reproduce the problem if I choose to show reports for an environment that is not default (production) or all of them (*).

**Comment by phybros** [comment]
Yeah my default env is "dev" and it's gotta be like that for reasons. Which part of the code handles that? Maybe I can make a PR

**Comment by tux-o-matic** [comment]
@phybros, you can start looking around the [/reports/json endpoint](https://github.com/voxpupuli/puppetboard/blob/v0.2.2/puppetboard/app.py#L478).
The problem is either in that endpoint or in pypuppetdb.

**Comment by mterzo** [comment]
What browser are you using and what version of jinja2 was installed from pip.

I upgraded my puppetdb to 4.4.0 and expected to run into a problem, but I'm not seeing any issues.  I went through the code and found:

https://github.com/voxpupuli/puppetboard/blob/v0.2.2/puppetboard/app.py#L474-L478

The sort order and by what comes from the client.

If you enable debug in the puppetboard, you can send the URL that was requested when you get the failure as well.  It's either browser encoding with javascript or jinja2 template issue.

**Comment by phybros** [comment]
sorry I was just on vacation, will check out jinja and the debug mode

**Comment by phybros** [comment]
Just hitting `/reports/json` with chrome produced this

```
[Wed May 31 15:14:06.407833 2017] [:error] [pid 19834] DEBUG:pypuppetdb.api:_query called with endpoint: environments, path: None, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None
[Wed May 31 15:14:06.408027 2017] [:error] [pid 19834] DEBUG:pypuppetdb.api:_url called with endpoint: environments and path: None
[Wed May 31 15:14:06.408766 2017] [:error] [pid 19834] INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: puppetdb.dev.trello.local
[Wed May 31 15:14:06.423649 2017] [:error] [pid 19834] DEBUG:requests.packages.urllib3.connectionpool:"GET /pdb/query/v4/environments HTTP/1.1" 200 16
[Wed May 31 15:14:06.424192 2017] [:error] [pid 19834] DEBUG:pypuppetdb.api:_query called with endpoint: reports, path: None, query: ["and",["=", "environment", "dev"]], limit: 100, offset: 0, summarize_by None, count_by None, count_filter: None
[Wed May 31 15:14:06.424313 2017] [:error] [pid 19834] DEBUG:pypuppetdb.api:_url called with endpoint: reports and path: None
[Wed May 31 15:14:06.428953 2017] [:error] [pid 19834] DEBUG:requests.packages.urllib3.connectionpool:"GET /pdb/query/v4/reports?query=%5B%22and%22%2C%5B%22%3D%22%2C+%22environment%22%2C+%22dev%22%5D%5D&order_by=%5B%7B%22field%22%3A+%22end_time%22%2C+%22order%22%3A+%22None%22%7D%5D&limit=100&include_total=true&offset=0 HTTP/1.1" 400 103
[Wed May 31 15:14:06.429322 2017] [:error] [pid 19834] ERROR:pypuppetdb.api:Illegal value '{:field "end_time", :order "None"}' in :order_by; 'order' must be either 'asc' or 'desc' puppetdb.dev.trello.local:8080 over HTTP.
[Wed May 31 15:14:06.429681 2017] [:error] [pid 19834] ERROR:puppetboard.app:Exception on /reports/json [GET]
[Wed May 31 15:14:06.429742 2017] [:error] [pid 19834] Traceback (most recent call last):
[Wed May 31 15:14:06.429769 2017] [:error] [pid 19834]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Wed May 31 15:14:06.429796 2017] [:error] [pid 19834]     response = self.full_dispatch_request()
[Wed May 31 15:14:06.429819 2017] [:error] [pid 19834]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Wed May 31 15:14:06.429841 2017] [:error] [pid 19834]     rv = self.handle_user_exception(e)
[Wed May 31 15:14:06.429862 2017] [:error] [pid 19834]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Wed May 31 15:14:06.429882 2017] [:error] [pid 19834]     reraise(exc_type, exc_value, tb)
[Wed May 31 15:14:06.429902 2017] [:error] [pid 19834]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Wed May 31 15:14:06.429928 2017] [:error] [pid 19834]     rv = self.dispatch_request()
[Wed May 31 15:14:06.429950 2017] [:error] [pid 19834]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Wed May 31 15:14:06.429971 2017] [:error] [pid 19834]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed May 31 15:14:06.429992 2017] [:error] [pid 19834]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 550, in reports_ajax
[Wed May 31 15:14:06.430012 2017] [:error] [pid 19834]     for report in reports_events:
[Wed May 31 15:14:06.430032 2017] [:error] [pid 19834]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pypuppetdb/api.py", line 798, in reports
[Wed May 31 15:14:06.430053 2017] [:error] [pid 19834]     reports = self._query('reports', **kwargs)
[Wed May 31 15:14:06.430076 2017] [:error] [pid 19834]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/pypuppetdb/api.py", line 340, in _query
[Wed May 31 15:14:06.430097 2017] [:error] [pid 19834]     r.raise_for_status()
[Wed May 31 15:14:06.430117 2017] [:error] [pid 19834]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
[Wed May 31 15:14:06.430138 2017] [:error] [pid 19834]     raise HTTPError(http_error_msg, response=self)
[Wed May 31 15:14:06.430158 2017] [:error] [pid 19834] HTTPError: 400 Client Error: Bad Request
[Wed May 31 15:14:06.430250 2017] [:error] [pid 19834] DEBUG:pypuppetdb.api:_query called with endpoint: environments, path: None, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None
[Wed May 31 15:14:06.430346 2017] [:error] [pid 19834] DEBUG:pypuppetdb.api:_url called with endpoint: environments and path: None
[Wed May 31 15:14:06.436692 2017] [:error] [pid 19834] DEBUG:requests.packages.urllib3.connectionpool:"GET /pdb/query/v4/environments HTTP/1.1" 200 16
```

**Comment by mterzo** [comment]
What OS is this?  I want to try and set up vagrant testbed.

**Comment by mterzo** [comment]
Wasn't completely fixed by #386.

**Comment by phybros** [comment]
@mterzo Ubuntu Server 14.04

**Comment by phybros** [comment]
I have solved the problem - the issues all came from Apache being used as a reverse proxy. We had copied over some settings from other systems that are behind that same reverse proxy.

Basically the solution was basically, to change the `WSGIScriptAlias` source from `/` to

```
WSGIScriptAlias /puppetboard "/srv/puppetboard/puppetboard/wsgi.py"
```

And then in our reverse proxy section we had:

```
      SetOutputFilter INFLATE;proxy-html;DEFLATE;
      ProxyPass http://localhost:8083/
      ProxyPassReverse /
```

Which is now

```
      ProxyPass http://localhost:8083/puppetboard/
      ProxyPassReverse /puppetboard
      ProxyHTMLURLMap / /puppetboard/
```

We could probably get rid of the `ProxyHTMLURLMap` alltogether by changing one of the application settings so that it knows its under `/puppetboard`. But this works for now. Thanks for your patience.

**Comment by tux-o-matic** [comment]
I've seen the error while using Nginx in front of Puppetboard served via Gunicorn. Not sure what changed between 0.2.1 and 0.2.2 since the Nginx configuration is the same.

**Comment by mterzo** [comment]
The internal server error is pretty common when things are misconfigured.  This one was due to a pretty custom apache config getting in the way.

I've got MR that puts error handling in front of puppetdb setup. This will help logging and identify misconfiguration.
