### ISSUE TITLE
Fail to load Semantic-UI minified CSS in offline mode

### ISSUE THREAD

**Issue by volans-** [voxpupuli/puppetboard#458]
When in offline mode (`OFFLINE_MODE` set to `True`), Puppetboard seems to fail to load the Semantic-UI CSS.
The browser is trying to load the path `/offline/Semantic-UI-2.1.8/semantic.min.css` and it seems to not find a template for it, the logged exception is:

```
ERROR in app: Exception on /offline/Semantic-UI-2.1.8/semantic.min.css [GET]
Traceback (most recent call last):
  File "./venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "./venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "./venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "./venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "./venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "./venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./venv/lib/python3.5/site-packages/puppetboard/app.py", line 1105, in offline_static
    return Response(response=render_template('static/%s' % filename),
  File "./venv/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "./venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "./venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "./venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "./venv/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "./venv/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "./venv/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: static/Semantic-UI-2.1.8/semantic.min.css
```

From a quick look at the code it's not fully clear to me why only the Semantic-UI minified CSS is calling the `offline_static` url handler instead of the standard `static` one like all the other resources.

### Installation details
Puppetboard version: **0.3.0** (from PyPI)
Python version: **3.5.3**
OS: **Debian GNU/Linux 9.4 (stretch)**
Served via uwsgi and Apache with mod_proxy in front of it.

**Comment by volans-** [comment]
I've noticed that this was resolved in https://github.com/voxpupuli/puppetboard/commit/28566b351f84bc2d8016ffd5ccc9bd9106cba837, hence I'm resolving it as I guess that the next PyPI release will resolve the issue.

By any chance do you have any time estimation for the next release of Puppetboard?
