### ISSUE TITLE
new python package flask causing breakage

### ISSUE THREAD

**Issue by rismoney** [voxpupuli/puppetboard#470]
https://github.com/voxpupuli/puppetboard/blob/master/requirements.txt specifically is optimistic on flask.
Version 0.12.14 works correctly.

Version 1.0.2 produces the following:

```
[2018-05-29 19:07:06 +0000] [648] [INFO] Starting gunicorn 19.7.1
[2018-05-29 19:07:06 +0000] [648] [INFO] Listening at: http://0.0.0.0:9000 (648)
[2018-05-29 19:07:06 +0000] [648] [INFO] Using worker: sync
[2018-05-29 19:07:06 +0000] [653] [INFO] Booting worker with pid: 653
[2018-05-29 19:07:07 +0000] [653] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/site-packages/puppetboard/app.py", line 23, in <module>
    from puppetboard.forms import (CatalogForm, QueryForm)
  File "/usr/local/lib/python2.7/site-packages/puppetboard/forms.py", line 4, in <module>
    from flask.ext.wtf import Form
ImportError: No module named ext.wtf
[2018-05-29 19:07:07 +0000] [653] [INFO] Worker exiting (pid: 653)
[2018-05-29 19:07:07 +0000] [648] [INFO] Shutting down: Master
[2018-05-29 19:07:07 +0000] [648] [INFO] Reason: Worker failed to boot.
```

**Comment by rismoney** [comment]
"/usr/local/lib/python2.7/site-packages/puppetboard/forms.py"

switching L4 to 
`from flask_wtf import Form`

**Comment by jvperrin** [comment]
This was already fixed more than a year ago in https://github.com/voxpupuli/puppetboard/commit/c59607564ae1ad74e46fbc39ca097d825165f8e6, are you running a puppetboard version before 0.3.0? Upgrading to the latest released version (0.3.0) should resolve this issue.

**Comment by rismoney** [comment]
Was using the docker container here- https://hub.docker.com/r/puppet/puppetboard/ is apparently on an older 0.2.2 release.  Odd because it was updated just over a week ago, but looks like it is pinned to that release.

**Comment by dot1q** [comment]
Yeah, I don't think the [puppet-in-docker](https://github.com/puppetlabs/puppet-in-docker/tree/master/puppetserver) repo is quite up to date. I guess it also doesn't go through any integration tests to make sure its images actually work with up to date dependencies either. 

I got a work around by forking puppet-in-docker and modifying the Dockerfile
https://hub.docker.com/r/gbrewster/puppetboard/ 
https://github.com/dot1q/puppet-in-docker/blob/master/puppetboard/Dockerfile

I believe this is an issue with the puppet-in-docker repo which updates to the dockerhub puppet account.

**Comment by mterzo** [comment]
Puppet in docker finally took some changes I submitted a while ago. I keep terzom/puppetboard up-to-date with pypi releases and somewhat with master.

**Comment by rismoney** [comment]
closing - using new version
