### ISSUE TITLE
PuppetDB Query Fails when Exported Resource contains Dictionary

### ISSUE THREAD

**Issue by yakatz** [voxpupuli/puppetboard#494]
We have an exported resource and we just added a large hash in it. This Puppetboard query stopped working as soon as the hash was added.

`["=", "exported", true]`

We now get this error:
```[2019-02-05 13:38:04,271] ERROR in app: Exception on /query [POST]
Traceback (most recent call last):
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 783, in query
    current_env=env)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/puppetboard/puppetboard/puppetboard/templates/query.html", line 1, in top-level template code
    {% extends 'layout.html' %}
  File "/srv/puppetboard/puppetboard/puppetboard/templates/layout.html", line 96, in top-level template code
    {% block content %} {% endblock content %}
  File "/srv/puppetboard/puppetboard/puppetboard/templates/query.html", line 47, in block "content"
    {{ result|prettyprint}}
  File "/srv/puppetboard/puppetboard/puppetboard/utils.py", line 92, in prettyprint
    html += "<td>" + formatvalue(e[k]) + "</td>"
  File "/srv/puppetboard/puppetboard/puppetboard/utils.py", line 74, in formatvalue
    ret += k + " => " + formatvalue(value[k]) + ",<br/>"
  File "/srv/puppetboard/puppetboard/puppetboard/utils.py", line 74, in formatvalue
    ret += k + " => " + formatvalue(value[k]) + ",<br/>"
  File "/srv/puppetboard/puppetboard/puppetboard/utils.py", line 74, in formatvalue
    ret += k + " => " + formatvalue(value[k]) + ",<br/>"
  File "/srv/puppetboard/puppetboard/puppetboard/utils.py", line 74, in formatvalue
    ret += k + " => " + formatvalue(value[k]) + ",<br/>"
  File "/srv/puppetboard/puppetboard/puppetboard/utils.py", line 74, in formatvalue
    ret += k + " => " + formatvalue(value[k]) + ",<br/>"
  File "/srv/puppetboard/puppetboard/puppetboard/utils.py", line 74, in formatvalue
    ret += k + " => " + formatvalue(value[k]) + ",<br/>"
  File "/srv/puppetboard/puppetboard/puppetboard/utils.py", line 70, in formatvalue
    return ", ".join(value)
TypeError: sequence item 0: expected string or Unicode, dict found
```

**Comment by gdubicki** [comment]
It works for me on the latest version of Puppetboard:

![Screenshot 2022-02-05 at 12 11 54](https://user-images.githubusercontent.com/566632/152641592-91eeba30-838e-44da-9ee0-532c450a924e.png)

Please update to it and reopen if you will still have the issue.
