### ISSUE TITLE
Fact with Unicode value is not displayed consistently and breaks formatted queries.

### ISSUE THREAD

**Issue by skrussell** [voxpupuli/puppetboard#509]
Puppetboard version: 1.0.0

We have a custom fact that scrapes, among other things, all the available system locales (using `localedef --list-archive`), which on some systems happens to contain the value "français" (note the cedilla character: "ç") - a perfectly legitimate value for a fact.

When using the "Query" page, and any query that would return that fact value, we get an "Internal Server Error", however, if you select "Raw JSON", the query completes successfully and the json output is displayed. (The value shows as "`fran\u00e7ais`", which isn't correct, but still, at least it doesn't die.)

The full error stack is:
```
ERROR:flask.app:Exception on /query [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/puppetboard/app.py", line 793, in query
    current_env=env)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/puppetboard/templates/query.html", line 1, in top-level template code
    {% extends 'layout.html' %}
  File "/usr/lib/python2.7/site-packages/puppetboard/templates/layout.html", line 97, in top-level template code
    {% block content %} {% endblock content %}
  File "/usr/lib/python2.7/site-packages/puppetboard/templates/query.html", line 47, in block "content"
    {{ result|prettyprint}}
  File "/usr/lib/python2.7/site-packages/puppetboard/utils.py", line 92, in prettyprint
    html += "<td>" + formatvalue(e[k]) + "</td>"
  File "/usr/lib/python2.7/site-packages/puppetboard/utils.py", line 74, in formatvalue
    ret += k + " => " + formatvalue(value[k]) + ",<br/>"
  File "/usr/lib/python2.7/site-packages/puppetboard/utils.py", line 70, in formatvalue
    return ", ".join(map(formatvalue, value))
  File "/usr/lib/python2.7/site-packages/puppetboard/utils.py", line 77, in formatvalue
    return str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe5' in position 4: ordinal not in range(128)
```

When browsing the node fact information, it is displayed differently, as "`fran\xe7ais`" instead (which is still incorrect, but again, at least it also doesn't die).

Can we please make this:
a) Not error when running the non-JSON query
and hopefully:
b) Correctly and consistently handle UTF-8 values

**Comment by bastelfreak** [comment]
Hi @skrussell, thanks for reporting this. Are you able to provide a PR for both requests?

**Comment by skrussell** [comment]
I wish I could @bastelfreak, but sadly programming is not my forte, especially a complex python web application...

**Comment by gdubicki** [comment]
I am closing this as it is most probably not affecting Puppetboard since we moved to Python 3 with a default support for unicode strings. Please reopen if you are still affected by this in a current version of the app. Thanks!
