### ISSUE TITLE
Overview / Metrics / Radiator not working

### ISSUE THREAD

**Issue by cartera93** [voxpupuli/puppetboard#566]
When we select "All environments" the "Overview", "Metrics", and "Radiator" pages return this error
> Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This error is also returned by the "Metrics" page with any specific environment selected but the "Overview" and "Radiator" pages work for those.

We are running puppetboard 2.1.2 in a docker container with pypuppetdb 2.1.0 and PuppetDB 6.9.1

**Comment by bgibson710** [comment]
We downgraded puppetdb to 6.9.0 and things again work as they should.  Seems like the changes for the new API aren't fully in place even though the change logs seem to indicate they should be?  Is there something we're missing?

**Comment by shoddyguard** [comment]
Similar issue here but only with Metrics not working - downgrading PuppetDB to 6.9.0 also fixed this issue for me.

Some syslog goodness in case it helps:
```
Apr 27 00:45:40 vagrant docker-puppetboard[704]: 10.0.2.2 - - [27/Apr/2020:00:45:40 +0000] "GET /metrics HTTP/1.1" 500 290 "http://127.0.0.1:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/$
Apr 27 00:45:40 vagrant docker-puppetboard[704]: ERROR:puppetboard.core:Exception on /metrics [GET]
Apr 27 00:45:40 vagrant docker-puppetboard[704]: Traceback (most recent call last):
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     response = self.full_dispatch_request()
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     rv = self.handle_user_exception(e)
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     reraise(exc_type, exc_value, tb)
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     raise value
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     rv = self.dispatch_request()
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/src/app/puppetboard/app.py", line 864, in metrics
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     metrics_domains = get_or_abort(puppetdb.metric)
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/src/app/puppetboard/utils.py", line 99, in get_or_abort
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     return func(*args, **kwargs)
Apr 27 00:45:40 vagrant docker-puppetboard[704]:   File "/usr/local/lib/python3.8/site-packages/pypuppetdb/api.py", line 927, in metric
Apr 27 00:45:40 vagrant docker-puppetboard[704]:     raise DoesNotComputeError(res['error'])
Apr 27 00:45:40 vagrant docker-puppetboard[704]: pypuppetdb.errors.DoesNotComputeError: java.lang.Exception : No access from client 172.17.0.2 allowed
```

**Comment by oldNoakes** [comment]
We ran into this and found this documentation: https://puppet.com/docs/puppetserver/latest/metrics-api/v2/metrics_api.html#configuring-jolokia which seemed to align with the errors we were seeing on the puppetdb side (access not allowed for client).

That said, we were unable to make this work - if anyone else gets this working and can provide a working example, please could you post?  Is this where we should be looking?

**Comment by oldNoakes** [comment]
@bastelfreak - just wanted to ask if you have a working example - I can see the discussion going on around this:
* https://github.com/voxpupuli/pypuppetdb/issues/172
* https://github.com/voxpupuli/puppetboard/pull/558

but are you successfully running puppetboard remotely from the pupperserver?  If so, would you mind giving us a _redacted_ version of yours that can demonstrate the changes needed?

My jolokia-access.xml file looks like this but does not work:

```
<?xml version="1.0" encoding="utf-8"?>

<restrict>
  <remote>
    <host>127.0.0.1</host>
    <host>a.b.c.d</host>
  </remote>

  <commands>
    <command>read</command>
    <command>list</command>
    <command>version</command>
    <command>search</command>
  </commands>
</restrict>
```

where ```a.b.c.d``` is the direct IP of my puppetboard server.  I have tried restarting all services and can see in the puppetserver logs that it is reading this file and yet am still getting ```java.lang.Exception: No access from client a.b.c.d allowed``` in the puppetdb logs. 

A working example would be much appreciated - thank you!

**Comment by bgibson710** [comment]
I can confirm that the information provided above fixed our issue, and everything is working as expected after making these changes.  We probably just need the documentation updated to include these changes for the v2 API.

**Comment by pjamenaja** [comment]
Thanks a lot guys this helped me solved the issue. 

My puppetdb and puppetboard are in the same pod so I set the host in `/etc/puppetlabs/puppetdb/jolokia-access.xml` to `0.0.0.0/0` for simplicity.

>
      <remote>
        <host>0.0.0.0/0</host>
      </remote>

**Comment by raphink** [comment]
Note: we're still seeing this with PuppetDB 7, and it seems to be because there is now an `auth.conf` for PuppetDB which prevents unauthenticated requests to `/metrics`.

**Comment by gdubicki** [comment]
Can someone please provide a PR to add the required info to the app docs? @oldNoakes perhaps?

**Comment by blodone** [comment]
in /etc/puppetlabs/puppetdb/conf.d/auth.conf we had to set
`allow: *`
to
`allow-unauthenticated: true`

for
`name: "puppetlabs puppetdb metrics"`

restart puppetdb and puppetboard does not show Forbidden 403 anymore

**Comment by jcpunk** [comment]
For folks using the containers, I've opened https://tickets.puppetlabs.com/browse/PDB-5522 to give a place for this change to be done automatically.
