### ISSUE TITLE
Internal Server Error switching from default environment to All Environments

### ISSUE THREAD

**Issue by buzzdeee** [voxpupuli/puppetboard#727]
**Describe the bug**

When in the puppetboard UI in the upper right corner, switching from the default environment "production" to "All Environments", the UI shows me an Internal Server Error.

puppetboard logs show:

`ERROR:puppetboard.utils:java.lang.Exception : No access from client 10.0.0.41 allowed`

puppetdb logs show:

```
2022-12-13 22:14:42,117 ERROR [p.t.s.m.jolokia] Error 403
java.lang.Exception: No access from client 10.0.0.41 allowed
        at org.jolokia.http.HttpRequestHandler.handleThrowable(HttpRequestHandler.java:242)
        at org.jolokia.http.AgentServlet.handle(AgentServlet.java:324)
        at org.jolokia.http.AgentServlet.doGet(AgentServlet.java:277)
        at puppetlabs.trapperkeeper.services.metrics.jolokia.proxy$org.jolokia.http.AgentServlet$ff19274a.doGet(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at puppetlabs.trapperkeeper.services.metrics.jolokia.proxy$org.jolokia.http.AgentServlet$ff19274a.service(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at puppetlabs.trapperkeeper.services.metrics.jolokia.proxy$org.jolokia.http.AgentServlet$ff19274a.service(Unknown Source)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at com.puppetlabs.trapperkeeper.services.webserver.jetty9.utils.MDCRequestLogHandler.handle(MDCRequestLogHandler.java:36)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:750)
```

Note: I only have a single environment "production"

**Puppetboard version**

puppetboard 4.2.3 (but it seems, also the problem existed with 4.0.5)

**Environment and installation method**

py-puppetdb 3.1.0
puppetdb 5.2.19
Python 3.10.8
OS: OpenBSD 7.2 amd64

all installed from OpenBSD packages.

**Comment by gdubicki** [comment]
Hi @buzzdeee!

Isn't your issue similar to #673? It looks like you need to reconfigure your PuppetDB to allow more access for the Puppetboard.
